version: '3'

networks:
  grafana:

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - ./grafana-storage:/var/lib/grafana grafana/grafana-enterprise
    networks:
      - grafana
    ports:
      - 3008:3000