version: '3'

networks:
  grafana:

services:
  grafana:
    image: grafana
    container_name: grafana
    volumes:
      - ./grafana-storage:/var/lib/grafana grafana/grafana-enterprise
    networks:
      - grafana
    ports:
      - 3000:3008

  prometheus:
    image: prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml 
    networks:
      - grafana
    ports:
      - 9090:9090