version: "3"
services:
  mongo1:
    hostname: mongo1
    image: mongo
    expose:
      - 27017
    ports:
      - 27017:27017
    restart: always
    command: --replSet rs0 --bind_ip_all
    volumes:
      - ../DB/localMongoData/db:/data/db
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --quiet) -eq 1
      interval: 10s
    # logging:
    #   driver: none

  mongo2:
    hostname: mongo2
    image: mongo
    expose:
      - 27017
    ports:
      - 27018:27017
    restart: always
    command: --replSet rs0 --bind_ip_all
    # logging:
    #   driver: none

  mongo3:
    hostname: mongo3
    image: mongo
    expose:
      - 27017
    ports:
      - 27019:27017
    restart: always
    command: --replSet rs0 --bind_ip_all
    # logging:
    #   driver: none
