version: '3'
networks:
  neo4j:

services:
 postgres:
    image: neo4j
    volumes:
      - ./data:/data
    environment:
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_AUTH: anh/ZGViZXppdW1zb3VyY2U=
    healthcheck:
      test: [ "CMD-SHELL", "echo RETURN 1 | cypher-shell -a <NEO4J_dbms_connector_bolt_listen__address> -u <user defined username> -p <user defined password> || exit 1" ]
    networks:
      - neo4j
    ports:
      - 7474:7474