version: '3'
networks:
  postgres:

services:
 postgres:
    image: postgres
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ZGViZXppdW1zb3VyY2U=
    networks:
      - postgres
    ports:
      - 1433:1433

 adminer:
    image: adminer
    restart: always
    networks:
      - postgres
    ports:
      - 8080:8080