version: '3'

networks:
  mssql:

services:
  mssql:
    image: microsoft/mssql:latest
    container_name: mssql
    
    volumes:
      - ./redis-data/:/data
    networks:
      - redis
    ports:
      - 6379:6379