version: '3'

networks:
  mongo:

services:
  mongo:
    image: mongo
    restart: always
    # ports:
    #   - 27017:27017
    networks:
      - mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: anh
      MONGO_INITDB_ROOT_PASSWORD: ZGViZXppdW1zb3VyY2U=

  mongo-express:
    image: mongo-express
    restart: always
    networks:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: anh
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://anh:ZGViZXppdW1zb3VyY2U=@mongo:27017/